donasi/urls.py
from donasi.views import seeInstitution
from django.urls import path
from . import views

app_name = 'donasi'

urlpatterns = [
    path('', views.institutionReg, name="institution"),
    path('seeInstitution/', views.seeInstitution, name="seeInstitution"),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('donate/', views.donate, name='donate')
]

ppw_kel_12/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('donations/', include('daftarDonasi.urls')),
    path('reportIssue/', include('report.urls')),
    path('question/', include('pertanyaan.urls')),
    path('testi/', include('testi.urls')),
    path('institution/', include('donasi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

donasi/models.py
from django.db import models

# Create your models here.
class Donasi(models.Model):
    lembaga = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=500, null=True)
    image = models.ImageField(upload_to="img/", default="default.png", blank=True)

donasi/forms.py
from django import forms
from .models import Donasi

class FormLembaga(forms.ModelForm):
    class Meta :
        model = Donasi
        fields = '__all__'

        widgets = {
            'lembaga' : forms.TextInput(attrs={'placeholder':'Name'}),
            'description' : forms.Textarea(attrs={'placeholder':'Description'}),
        }

donasi/views.py
from donasi.forms import FormLembaga
from django.shortcuts import render, redirect
from .models import Donasi

# Create your views here.
def institutionReg(request):
    form = FormLembaga()
    context = {'form':form}
    if request.method == "POST": 
        form = FormLembaga(request.POST, request.FILES)
        if form.is_valid(): 
            form.save()
        return redirect('/institution')

    return render(request, 'donasi/donasi.html', context)

def seeInstitution(request):
    institution = Donasi.objects.all()
    context = {'institution':institution}

    return render(request, 'donasi/lihat.html', context)

donasi/templates/donasi/donasi.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>
    <head>
        {% block meta %}
        <style>
            h1 {
                text-align: center;
            }

            input, textarea {
                border-radius: 80px;
            }

            input, textarea, ::placeholder {
                text-align: center;
            }

            textarea {
                width: 50%;
            }

            .table {
                text-align: center;
            }
        </style>
        <title>Add Institution</title>
        {% endblock meta %}
    </head>

    <body>
        {% block content %}
        <h1 style="color: #4B6574; font-weight: bold; ">Register Your Institution</h1>
        <form method="POST" enctype="multipart/form-data">
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            {{ form.lembaga }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form.description }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form.image }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {% csrf_token %}
                            <button class="btn btn-light" type="submit" name="Simpan">Submit</button>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="{% url 'donasi:seeInstitution' %}" style="color: black;">See Institutions</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>     
        {% endblock %}
    </body>
</html>

donasi/templates/donasi/lihat.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>
    <head>
    {% block meta %}
    <style>
        .my-custom-scrollbar {
            position: relative;
            max-height: 470px;
            overflow: auto;
        }
        .table-wrapper-scroll-y {
            display: block;
        }
        .gambar {
            width: 10%;
        }
    </style>
    <title>Our Institution</title>
    {% endblock meta %}
    </head>

    <body>
        {% block content %}
        <div class="container" style="margin: 5%;">
            <div class="row justify-content-between">
                <div class="col-5 align-self-start" style="margin-top:10%">
                    <h1 style="color: #4B6574; font-weight: bold; ">Our Partner<br>Intitutions</h1>
                </div>

                <div class="table-wrapper-scroll-y my-custom-scrollbar" style="width: 55%;">
                    <table class="table table-borderless mb-0">
                        <tbody>
                            {% for i in institution %}
                            <tr>
                                <td class="gambar">
                                    <img src="{{ i.image.url }}" class="mr-3" alt="{{ i.lembaga }}" width="60">
                                </td>
                                <td><h5>{{ i.lembaga }}</h5>
                                <p>{{ i.description }}<p>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% endblock %}
    </body>
</html>