donasi/urls.py
from donasi.views import seeInstitution
from django.urls import path
from . import views

app_name = 'donasi'

urlpatterns = [
    path('', views.institutionReg, name="institution"),
    path('seeInstitution/', views.seeInstitution, name="seeInstitution"),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('donate/', views.donate, name='donate')
]

pertanyaan/urls.py
from django.urls import path

from . import views

app_name = 'pertanyaan'

urlpatterns = [
    path('', views.pertanyaan, name='pertanyaan'),
    path('<str:pk>/', views.detail, name='detail'),
]

ppw_kel_12/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('donations/', include('daftarDonasi.urls')),
    path('reportIssue/', include('report.urls')),
    path('question/', include('pertanyaan.urls')),
    path('testi/', include('testi.urls')),
    path('institution/', include('donasi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('', views.report, name="report"),
    path('lihatReport/', views.lihat, name="lihat")
]

testi/urls.py
from django.urls import path, include
from . import views
app_name = 'testi'

urlpatterns = [
    path('', views.tampilan, name='tampilan'),
    path('atur/', views.testi, name='testi'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'daftarDonasi/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'testi/style.css' %}"> {% block meta %} {% endblock meta %}
</head>

<body>
    <div class="navbar navbar-expand-lg navbar-light nav">
        <a class="navbar-brand" href="{% url 'main:home'%}">
            <img src="/static/img/logo.png" width="40" height="40" alt="">
        </a>
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navv">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse nav" id="navv">
            <ul class="navbar-nav mr-auto">
                <li>
                    <a href="{% url 'main:home'%}">Home</a>
                </li>
                <li>
                    <a href="{% url 'main:donate'%}">Donate</a>
                </li>
                <li>
                    <a href="{% url 'daftarDonasi:daftarDonasi'%}">Donations</a>
                </li>
                <li>
                    <a href="{% url 'testi:tampilan' %}">Testimonies</a>
                </li>
                <li>
                    <a href="{% url 'pertanyaan:pertanyaan'%}">Questions</a>
                </li>
                <li>
                  <a href="{% url 'donasi:institution'%}">Institution</a>
                </li>
                <li>
                    <a href="{% url 'report:report'%}">Reports</a>
                </li>
            </ul>
        </div>
    </div>
    {% block content %} {% endblock content %}
    <footer></footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>

</html>