main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('donate/', views.donate, name='donate')
]

ppw_kel_12/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('donations/', include('daftarDonasi.urls')),
    path('reportIssue/', include('report.urls')),
    path('question/', include('pertanyaan.urls')),
    path('testi/', include('testi.urls')),
    path('institution/', include('donasi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testi/urls.py
from django.urls import path, include
from . import views
app_name = 'testi'

urlpatterns = [
    path('', views.tampilan, name='tampilan'),
    path('atur/', views.testi, name='testi'),
]

testi/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.
class Testi(models.Model):
    nama = models.CharField(max_length = 100)
    institusi=models.CharField(max_length=100)
    testimoni = models.TextField(max_length = 1000)
    tanggal_testi = models.DateField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['institusi','nama']),
            models.Index(fields=['nama'], name='nama_idx'),
        ]
    def __str__(self):
        return self.nama

testi/forms.py
from django import forms
from .models import Testi
# Create your views here.

class Testimoni_Form(forms.ModelForm):
    class Meta:
        model = Testi
        fields = [
            'nama',
            'institusi',
            'testimoni'
        ]
        widgets = {
            'nama': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Name'
				}
			),
            'institusi': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Institution'
				}
			),
            'testimoni': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Testimonial',
                    'height':400 
				}
			)
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        

testi/views.py
from django.shortcuts import render, redirect
from .forms import Testimoni_Form
from .models import Testi

def tampilan(request):
    testi = Testi.objects.all()
    context = {
        'semua_testi':testi
    }
    return render(request, 'tampilanTesti.html', context)

def testi(request):
    testi_form = Testimoni_Form(request.POST or None)
    if request.method == "POST":
        if testi_form.is_valid():
            testi_form.save()

        return redirect('testi:tampilan')
    
    context = {
        'testi_form' : testi_form
    }
    return render(request, 'isiTesti.html', context)

testi/templates/isiTesti.html
{% extends 'base.html' %} {% block content%}
<h1 style="color: #4B6574; font-weight: bold; padding-left: 10%; padding-top: 5%;">Give Us Testimonial
</h1>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="id_nama">Name:*</label> {{testi_form.nama}}
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="id_institusi">Institution:*</label> {{testi_form.institusi}}
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="id_testimoni">Testimonial:</label> {{testi_form.testimoni}}
        </div>

        <button type="submit" class="btn btn-light">Submit</button>
        <a href="{% url 'testi:tampilan' %}" style="color: black;"> See All </a>
    </form>
</div>
{% endblock %}

testi/templates/tampilanTesti.html
 {% extends 'base.html' %} {% block content%}
<!DOCTYPE html>
<html>

<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        
        html,
        body,
        .Container {
            height: 100%;
        }
        
        .Container:before {
            content: '';
            height: 100%;
            float: right;
        }
        
        .Footer {
            margin-bottom: 10px;
            background-color: #91b14c;
        }
        
        .Content {
            position: relative;
            z-index: 1;
        }
        
        .Content:after {
            content: '';
            clear: both;
            display: block;
        }
        
        .Wrapper {
            position: absolute;
            width: 100%;
            height: 100%;
        }
        
        .Wrapper>div {
            height: 100%;
        }
        
        .RightContent {
            overflow: hidden;
        }
        
        .RightContent:hover {
            overflow: auto;
        }
        
        .LeftContent {
            float: left;
            width: 50%;
        }
        
        div.card-header.text-center {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
        }
        
        .card-header {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }
        
        a {
            text-decoration: none;
        }
    </style>
</head>

<body>
    <div class="Container">
        <div class="Content">
            <div class="Wrapper">
                <div class="LeftContent" style="padding-left: 10%;padding-top: 5%;">
                    <b><h1 style="color: #4B6574; font-weight: bold; ">
                        What Do<br>People Say<br>About Us?
                    </h1></b>
                    <a style="margin-bottom: 30px;" href="{% url 'testi:testi' %}" class="btn btn-light">Give Us Testimoni</a>
                </div>
                <div class="RightContent" style="padding-top: 2.5%;padding-right: 2.5%; ">
                    {% for itu in semua_testi %}
                    <div class="card" style="width: 100%; margin-bottom: 10px;">
                        <div class="card-header" style="width: 100%;">
                            <div style="width: 100%;">
                                <h3>
                                    <center><b>{{itu.nama}}</b>, <u>{{itu.institusi}}</u></center>
                                </h3>
                            </div>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <center>
                                    <p>{{itu.testimoni}}</p>
                                </center>
                                <p style="text-align: right;">{{itu.tanggal_testi}}</p>
                            </li>

                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="Footer"><br><br></div>
</body>

</html>
{% endblock %}